config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
    unauthenticated do
      root 'pages#index', as: :unauthenticated_root
    end
  end

  resources :categories, only: [:index, :new, :create] do
    resources :transaktions, only: [:index, :new, :create] do
      resources :categorie_transaktions, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, :all if user.role == 'admin'
    can :manage, :all if user.role == 'default'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorie.rb
class Categorie < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categorie_transaktions
  has_many :transaktions, through: :categorie_transaktions

  validates :name, presence: true, length: { maximum: 25 }
  validates :icon, presence: true, length: { maximum: 250 }

  def name_with_initial
    'pratap'
  end
end

app/models/categorie_transaktion.rb
class CategorieTransaktion < ApplicationRecord
  belongs_to :categorie
  belongs_to :transaktion

  validates :categorie, presence: true
  validates :transaktion, presence: true
end

app/models/transaktion.rb
class Transaktion < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categorie_transaktions
  has_many :categories, through: :categorie_transaktions

  validates :author_id, presence: true
  validates :name, presence: true, length: { maximum: 25 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'author_id', class_name: 'Categorie'
  has_many :transaktions, foreign_key: 'author_id', class_name: 'Transaktion'

  validates :name, presence: true, length: { maximum: 25 }
  ROLES = %i[admin default].freeze
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # private
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :role)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_author

  def index
    @categories = @author.categories
  end

  def new
    @categorie = Categorie.new
  end

  def show
    @categorie = Categorie.find(params[:id])
    @transaktions = []
    @categorie.categorie_transaktions.order(:id).each do |some|
      @transaktions.push(some.transaktion)
    end
  end

  def create
    @categorie = Categorie.new(categorie_params)
    @categorie.author = @author
    if @categorie.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def categorie_params
    params.require(:categorie).permit(:name, :icon)
  end
end

private

def set_author
  @author = current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @user = current_user
    redirect_to categories_path if user_signed_in?
  end

  # private
  # def user_params
  #   params.require(:user).permit(:id)
  # end
end

app/controllers/transaktions_controller.rb
class TransaktionsController < ApplicationController
  before_action :set_author

  def index
    @categories = @author.categories
    @categorie = @categories.find(params[:category_id])
    @transaktions = @categorie.transaktions
  end

  def new
    @categories = @author.categories
    @categorie = Categorie.find(params[:category_id])
    @transaktion = Transaktion.new
  end

  def create
    @categorie = Categorie.find_by(cat_params)
    @transaktion = @author.transaktions.new(transaktion_params)
    return unless @transaktion.save

    @categorie_transaktion = CategorieTransaktion.new(transaktion: @transaktion, categorie: @categorie)
    redirect_to category_transaktions_path(@categorie.id) if @categorie_transaktion.save
  end

  private

  def transaktion_params
    params.require(:transaktion).permit(:name, :amount)
  end

  def cat_params
    params.require(:transaktion).permit(:id)
  end
end

private

def set_author
  @author = current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transaktions_helper.rb
module TransaktionsHelper
end

app/views/categories/index.html.erb
<div class=grid-container>
  <div class=grid-item>
    <p>
      Signed in as
    </p>
    <%= @author.email %>
  </div>
  <div class='grid-item text'>
    CATAGORIES
  </div>
  <% if user_signed_in? %>
    <div class=grid-item>
      <%= button_to 'SIGN OUT', destroy_user_session_path, method: :delete, data: {turbo: false}, class: 'link-white' %>
    </div>
  <% end %>
</div>
<div class=categorie-container>
  <% @categories.each do |categorie| %>
    <%= link_to category_transaktions_path(categorie.id), class: 'cards' do %>
      <div class=categorie-card>
        <div class=column>
          <img src="<%= categorie.icon %>" width=60 height=60>
        </div>
        <div class=column>
          <div class=c434b54>
            <%= categorie.name %>
          </div>
        </div>
        <div class=column>
          <div class=c434b54>
            <%= categorie.categorie_transaktions.sum {|x| x.transaktion.amount } %>$
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class=link-margin>
    <%= link_to 'Add a new Categorie', new_category_path, class: 'link-style' %>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_with model: @categorie, local: true do |f| %>
  <div class=grid-container>
    <div class=grid-item>
      <%= link_to image_tag(asset_path('back-arrow-icon.svg'), class: 'back-arrow'), authenticated_root_path %>
    </div>
    <div class=grid-item>
      <div class=text>
        CATAGORIE
      </div>
    </div>
    <div class=grid-item>
      <%= f.submit "SAVE", data: {turbo: false} %>
    </div>
  </div>
  <%= f.text_field :name, placeholder: 'Name', class: 'input-field' %>
  <%= f.text_field :icon, placeholder: 'Image URL', class: 'input-field' %>
<% end %>
<div class=note>
  Hi <%= @author.name %>, you are creating a categorie.
  once you input 'Name' and 'Image url', click enter or save button.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class=app-name>
  <h1>Budget App</h1>
</div>

<div class=flex-column>
  <%= link_to 'LOG IN', new_user_session_path, class: 'login' %>
  <%= link_to 'SIGN UP', new_user_registration_path, class: 'signup' %>
</div>

app/views/transaktions/index.html.erb
<div class=grid-container>
  <div class=grid-item>
    <%= link_to image_tag(asset_path('back-arrow-icon.svg'), class: 'back-arrow'), authenticated_root_path %>
  </div>
  <div class='grid-item text'>
    TRANSACTIONS
  </div>
  <% if user_signed_in? %>
    <div class=grid-item>
      <%= button_to 'SIGN OUT', destroy_user_session_path, method: :delete, data: {turbo: false}, class: 'link-white' %>
    </div>
  <% end %>
</div>
<div class=whitebar>
  <div>
    Total Amount
  </div>
  <div>
    <%= @categorie.transaktions.sum {|x| x.amount } %>$
  </div>
</div>
<div class=categorie-container>
  <% @transaktions.order(created_at: :desc).each do |transaktion| %>
    <div class=transaktion-card>
      <div class=space-between>
        <p>
          <%= transaktion.name %>
        </p>
        <p>
          <%= transaktion.amount %>$
        </p>
      </div>
    </div>
  <% end %>
  <div class=link-margin>
    <%= link_to 'Add a new Transaction', new_category_transaktion_path(params[:category_id]), class: 'link-style' %>
  </div>
</div>
<div class=center-single-div>
  <img src="<%= @categorie.icon %>" width=30 height=30>
  <p>
    You are looking at <%= @categorie.name %> Categorie transactions
  </p>
</div>

app/views/transaktions/new.html.erb
<%= form_with model: @transaktion, url: category_transaktions_path, local: true do |f| %>
  <div class=grid-container>
    <div class=grid-item>
      <%= link_to image_tag(asset_path('back-arrow-icon.svg'), class: 'back-arrow'), category_transaktions_path(@categorie) %>
    </div>
    <div class=grid-item>
      <div class=text>
        TRANSACTION
      </div>
    </div>
    <div class=grid-item>
      <%= f.submit "SAVE", data: {turbo: false} %>
    </div>
  </div>
  <%= f.text_field :name, placeholder: 'Name', class: 'input-field' %>
  <%= f.text_field :amount, placeholder: 'Amount', class: 'input-field' %>
  <div class=jc-center>
    <%= f.select :id, options_for_select(@categories.collect { | x | [x.name, x.id] })%>
  </div>
<% end %>
<div class=note>
  Hi <%= @author.name %>, you are creating a Transaction.
  once you input 'Name', 'Amount' and choose the 'Categorie, click enter or save button.
</div>